pub use about::AboutPage;
pub use appearance::AppearancePage;
pub use bookmarks::BookmarksPage;
pub use connections::Connections;
pub use database_tools::DatabaseToolsPage;
pub use home::Home;
pub use keyboard_shortcuts::KeyboardShortcutsPage;
pub use layout::LayoutPage;
pub use not_found::NotFound;
pub use query::QueryEditor;
pub use query_history::QueryHistoryPage;
pub use quick_start::QuickStartPage;
pub use redb_browser::RedbBrowserPage;
pub use sql_utilities::SqlUtilitiesPage;
pub use table_structure::TableStructure;

mod about;
mod appearance;
mod bookmarks;
mod connections;
mod database_tools;
mod home;
mod keyboard_shortcuts;
mod layout;
mod not_found;
mod query;
mod query_history;
mod quick_start;
mod redb_browser;
mod sql_utilities;
mod table_structure;
