[build]
target = "./index.html"
integrity = "none"

[watch]
ignore = ["../domain", "../infrastructure", "../interfaces", "../application"]

[serve]
port = 1420
open = false

[[proxy]]
rewrite = "/api"
backend = "http://localhost:3000/api"

[[proxy]]
rewrite = "/health"
backend = "http://localhost:3000/health"
